#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     limit_switch,   sensorTouch)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     arm_tipper,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     flag_spinner,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     right_drive,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     left_drive,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

#include "gearcats_helpers.h"


bool played_sound;

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	left_drive_motor = left_drive;
	right_drive_motor = right_drive;
	played_sound = false;

  return;
}


task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.

  arcade_drive(60,20);
	wait1Msec(4000);
  while (true) {
  	arcade_drive(0,0);
  }

}
