#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     left_drive,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     right_drive,   tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    spinner,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bool going = true;
	while (going){
		servoTarget[spinner] = 160;
		motor[left_drive] = 100;
		motor[right_drive] = 100;
		wait1Msec(2000);
		motor[left_drive] = 0;
		motor[right_drive] = 0;
		going = false;
	}

}
